from lexer import *

if __name__ == '__main__':
    lexer_obj = Lexer("lexer_test1.txt")
    lexer_obj.getchar()
    assert (lexer_obj.char == "a")
    lexer_obj.getchar()
    assert (lexer_obj.char == "b")
    lexer_obj.getchar()
    assert (lexer_obj.char == "c")
    lexer_obj.getchar()
    assert (lexer_obj.char == "$")

    lexer_obj = Lexer("lexer_test1.txt")
    lexer_obj.getsym()
    assert (lexer_obj.token == "abc")

    lexer_obj = Lexer("lexer_test2.txt")
    lexer_obj.getsym()
    assert (lexer_obj.token == "abc")
    lexer_obj.getsym()
    assert (lexer_obj.symbol == "ADD")
    lexer_obj.getsym()
    assert (lexer_obj.token == "bc")
    lexer_obj.getsym()
    assert (lexer_obj.symbol == "MULT")
    lexer_obj.getsym()
    assert (lexer_obj.token == "a")
    lexer_obj.getsym()
    assert (lexer_obj.symbol == "ADD")
    lexer_obj.getsym()
    assert (lexer_obj.token == "c")
    lexer_obj.getsym()
    assert (lexer_obj.symbol == "ADD")
    lexer_obj.getsym()
    assert (lexer_obj.token == "abc")